name: supervision
channels:
  - pytorch
  - pyg
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - pytorch-geometric
  - pandas
  - numpy
  - scikit-learn
  - matplotlib
  - ase
  - pymatgen
  - matminer
  - transformers
  - pillow
  - requests
  - tqdm
  - joblib
  - pip
  - pip:
    - torch-geometric
